# Normal registration flow
#┌─────┐                    ┌─────┐                    ┌──────┐
#│ UE  │                    │ AMF │                    │ AUSF │
#└──┬──┘                    └──┬──┘                    └───┬──┘
#   │                          │                           │
#   │ Registration Request     │                           │
#   │ (SUPI, capabilities)     │                           │
#   ├─────────────────────────>│                           │
#   │                          │                           │
#   │                          │ Auth Vector Request       │
#   │                          ├──────────────────────────>│
#   │                          │                           │
#   │                          │ Auth Vector Response      │
#   │                          │<──────────────────────────┤
#   │                          │                           │
#   │ Authentication Request   │                           │
#   │ (RAND, AUTN)             │                           │
#   │<─────────────────────────┤                           │
#   │                          │                           │
#   │ Authentication Response  │                           │
#   │ (RES)                    │                           │
#   ├─────────────────────────>│                           │
#   │                          │ [Validates RES=XRES]      │
#   │                          │ [Creates UE context]      │
#   │                          │ [Assigns GUTI]            │
#   │                          │                           │
#   │ Registration Accept      │                           │
#   │ (GUTI, TAI list, NSSAI)  │                           │
#   │<─────────────────────────┤                           │
#   │                          │                           │
#   │ [UE stores GUTI]         │                           │
#   └──────────────────────────┴───────────────────────────┘
#
# AMF controller:
# - skip the auth part so do not communicate with the AUSF
# - registration response goes in Registration status
#
# Step 1: UE requests registration with network
# direction: "UE → AMF"
# interface: "N1 (NAS-MM)"
# message_type: "Registration Request"
# protocol: "NAS-MM"
apiVersion: amf.view.dcontroller.io/v1alpha1
kind: Registration
metadata:
  name: reg-1
  namespace: user-1
spec:
  registrationType: initial  # Options: initial | mobility | periodic | emergency  
  mobileIdentity:
    type: SUCI  # Options: SUPI | GUTI | IMEI | IMEISV | TMSI | SUCI
    value: "suci-0-999-01-02-4f2a7b9c8d13e7a5c0" # mapped
  ueSecurityCapability:
    encryptionAlgorithms:  # Ordered by preference (first = most preferred)
      - 5G-EA0  # Null encryption (no protection)
      - 5G-EA1  # 128-bit SNOW 3G
      - 5G-EA2  # 128-bit AES
      - 5G-EA3  # 128-bit ZUC
    integrityAlgorithms:  # Ordered by preference
      - 5G-IA0  # Null integrity (no protection) 
      - 5G-IA1  # 128-bit SNOW 3G
      - 5G-IA2  # 128-bit AES-CMAC
      - 5G-IA3  # 128-bit ZUC
  ueStatus:
    s1Mode: false  # EPC/LTE interworking capability
    n1Mode: true   # 5GC/NR native mode capability
  ueNetworkCapability:  # LTE/EPS capabilities for interworking
    epsEncryptionAlgorithms:
      - EEA0  # Options: EEA0, EEA1, EEA2, EEA3
    epsIntegrityAlgorithms:
      - EIA0  # Options: EIA0, EIA1, EIA2, EIA3
  requestedNSSAI:  # Requested network slices
    - sliceType: eMBB  # Options: eMBB | URLLC | MIoT | V2X | custom
      sliceDifferentiator: "000001"  # Optional, for multiple slices of same type
    - sliceType: URLLC
      sliceDifferentiator: "000002"

---
# Step 2: AMF completes registration and assigns context ID
# direction: "AMF → UE"
# interface: "N1 (NAS-MM)"
# message_type: "Registration Accept"
# protocol: "NAS-MM"
apiVersion: amf.view.dcontroller.io/v1alpha1
kind: Registration
metadata:
  name: reg-1
  namespace: user-1
spec:
  mobileIdentity:
    type: SUPI
    value: imsi-001010123456789
  registrationType: initial
  requestedNSSAI:
  - sliceDifferentiator: "000001"
    sliceType: eMBB
  - sliceDifferentiator: "000002"
    sliceType: URLLC
  ueNetworkCapability:
    epsEncryptionAlgorithms:
    - EEA0
    epsIntegrityAlgorithms:
    - EIA0
  ueSecurityCapability:
    encryptionAlgorithms:
    - 5G-EA0
    - 5G-EA1
    - 5G-EA2
    - 5G-EA3
    integrityAlgorithms:
    - 5G-IA0
    - 5G-IA1
    - 5G-IA2
    - 5G-IA3
  ueStatus:
    n1Mode: true
    s1Mode: false
status:
  conditions:
  - lastTransitionTime: "2025-10-30T15:44:17Z"
    message: Registration successful
    reason: Registered
    status: "True"
    type: Registered
  ueContext: ue_ctx_cstu0d
  
