# Step 1: UE requests registration with network
# direction: "UE → AMF"
# interface: "N1 (NAS-MM)"
# message_type: "Registration Request"
# protocol: "NAS-MM"
apiVersion: amf.view.dcontroller.io/v1alpha1
kind: Registration
metadata:
  name: reg-1
  namespace: default
description: "UE provides identity and capabilities for initial network registration"
spec:
  registration_type: 0x01  # Initial registration
  nas_key_set_identifier:
    tsc: 0  # Native security context
    nas_ksi: 0x07  # No key available yet
  mobile_identity:
    type: "SUPI"  # Subscription Permanent Identifier
    value: "imsi-001010123456789"
  ue_security_capability:
    encryption_algorithms: ["dummy"]
    integrity_algorithms: ["dummy"]
  ue_status:
    s1_mode: false  # Not using EPC
    n1_mode: true   # Using 5GC

---
# Step 2: AMF rejects registration with cause "Network failure"
# direction: "AMF → UE"
# interface: "N1 (NAS-MM)"
# message_type: "Registration Reject"
# protocol: "NAS-MM"
apiVersion: amf.view.dcontroller.io/v1alpha1
kind: Registration
metadata:
  name: reg-1
  namespace: default
description: "AMF accepts registration, establishes security, and provides UE context ID (in status)"
spec:
  registration_type: 0x01  # Initial registration
  nas_key_set_identifier:
    tsc: 0  # Native security context
    nas_ksi: 0x07  # No key available yet
  mobile_identity:
    type: "SUPI"  # Subscription Permanent Identifier
    value: "imsi-001010123456789"
  ue_security_capability:
    encryption_algorithms: ["dummy"]
    integrity_algorithms: ["dummy"]
  ue_status:
    s1_mode: false  # Not using EPC
    n1_mode: true   # Using 5GC
status:
  conditions:
    - type: Registered
      status: "False"
      lastTransitionTime: "2025-09-14T00:10:55Z"
      message: "Not registered"
    - type: SecurityContextEstablished
      status: "False"
      message: "Encryption algorithms not supported"
      lastTransitionTime: "2025-09-14T00:10:55Z"
