apiVersion: amf.view.dcontroller.io/v1alpha1
kind: Registration
metadata:
  name: user-1
  namespace: user-1
  labels:
    # Registration area (TAI where registration initiated)
    tracking.area: "tai-001-01-000001"
    # Equipment type (set after PEI check)
    equipment.type: "smartphone"  # enum: smartphone | iot | vehicle | etc
  annotations:
    # Protocol interface
    interface: "N1-NAS-MM"
    # RAN information
    ran.node: "gnb-site-4-sector-2"
spec:
  registrationType: initial  # Options: initial | mobility | periodic | emergency  
  accessType: "3gpp"  # enum: 3gpp | non-3gpp | both
  trackingArea: "tai-001-01-000001"
  mobileIdentity:
    type: SUCI  # Options: SUCI | SUPI | GUTI | IMEI | IMEISV | TMSI
    value: "suci-0-999-01-02-4f2a7b9c8d13e7a5c0"
  ueSecurityCapability:
    encryptionAlgorithms:  # Ordered by preference (first = most preferred)
      - 5G-EA0  # Null encryption (no protection)
      - 5G-EA1  # 128-bit SNOW 3G
      - 5G-EA2  # 128-bit AES
      - 5G-EA3  # 128-bit ZUC
    integrityAlgorithms:  # Ordered by preference
      - 5G-IA0  # Null integrity (no protection) 
      - 5G-IA1  # 128-bit SNOW 3G
      - 5G-IA2  # 128-bit AES-CMAC
      - 5G-IA3  # 128-bit ZUC
  ueStatus:
    s1Mode: false  # EPC/LTE interworking capability
    n1Mode: true   # 5GC/NR native mode capability
  ueNetworkCapability:  # LTE/EPS capabilities for interworking
    epsEncryptionAlgorithms:
      - EEA0  # Options: EEA0, EEA1, EEA2, EEA3
    epsIntegrityAlgorithms:
      - EIA0  # Options: EIA0, EIA1, EIA2, EIA3
  requestedNSSAI:  # Requested network slices
    - sliceType: eMBB  # Options: eMBB | URLLC | MIoT | V2X | custom
      sliceDifferentiator: "000001"  # Optional, for multiple slices of same type
    - sliceType: URLLC
      sliceDifferentiator: "000002"
